In [4]:
import numpy as np

In [5]:
# Function to return the sum of the sub-matrix
def get_sum(r1, r2, c1, c2, dp):
    return dp[r2][c2] - dp[r2][c1] - dp[r1][c2] + dp[r1][c1]

In [6]:
class Matrix:

    def __init__(self, random, rows ,cols):
        self.random = int(random)
        self.rows = int(rows)
        self.cols = int(cols)
        
    def create_random_matrix(self):
        A = np.random.randint(int(random), size=(int(rows), int(cols)))
        return A
    
    def sum_of_subsquares(self, k):
        mat = A
        n = len(mat)
        # k must be smaller than or equal to n
        if (k > n):
            return
        # row number of first cell in current
        # sub-square of size k x k
        for i in range(n - k + 1):
        # column of first cell in current
        # sub-square of size k x k
            for j in range(n - k + 1): 
            # Calculate and print sum of
            # current sub-square
                sum = 0
                for p in range(i, k + i):
                    for q in range(j, k + j):
                        sum += mat[p][q]
                print(sum, end = " ")
        
    def find_sum_boolean(self, k, s):
        mat = A
        n = len(mat)
        # 2-D array to store the sum of
        # all the sub-matrices
        dp = [[0 for i in range(n+1)] for j in range(n+1)]
        # Filling of dp[][] array
        for i in range(n):
            for j in range(n):
                dp[i + 1][j + 1] = dp[i + 1][j] + dp[i][j + 1] - dp[i][j] + mat[i][j]
                
        # Checking for each possible sub-matrix of size k X k
        for i in range(0, n):
            for j in range(0, n):
                sum = get_sum(i, i + k, j, j + k, dp)
                if (sum == s):
                    return True
 
        # Sub-matrix with the given sum not found
        return False

In [121]:
random = 10
rows = 5
cols = 5
m = Matrix(random, rows, cols)
A = m.create_random_matrix()
print(A)
m.sum_of_subsquares(2)
# the function returns the sum of any 2x2 matrix in matrix A (5x5)
m.find_sum_boolean(2,10)
# the function returns a boolean value after looking up if the sum of 10 in a 2x2 matrix 
# is present in a bigger matrix A (5x5)

[[9 7 1 8 4]
 [2 1 1 0 8]
 [4 3 5 2 1]
 [1 7 4 8 7]
 [1 2 4 8 0]]
19 10 10 20 10 10 8 11 15 19 19 18 11 17 24 23 

True